// <auto-generated />
using System;
using BlackjackRazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackjackRazor.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251028145617_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("BlackjackRazor.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BankrollEnd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BankrollStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("DealerBlackjacks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealerBusts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealerWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeckCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeckId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultBet")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HandsPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerBlackjacks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerBusts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pushes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BlackjackRazor.Data.Hand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Bet")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Payout")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlayedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasDouble")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasSplit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "HandIndex")
                        .IsUnique();

                    b.ToTable("Hands");
                });

            modelBuilder.Entity("BlackjackRazor.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlackjackRazor.Data.Game", b =>
                {
                    b.HasOne("BlackjackRazor.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlackjackRazor.Data.Hand", b =>
                {
                    b.HasOne("BlackjackRazor.Data.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
